tweet_project/tweet_app/urls.py
from django.urls import path,reverse,reverse_lazy
from . import views
app_name="tweet_app"


urlpatterns = [
    path("",views.listtweet,name="listtweet"),
    path("add/",views.addtweet,name="addtweet"),
    path("signup/",views.signup.as_view(),name="signup"),
    path("deletetweet/<int:id>",views.delete,name="deletetweet"),
]

tweet_project/tweet_project/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("tweet_app.urls")),
    path("", include("django.contrib.auth.urls")),
]

tweet_project/tweet_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Tweets(models.Model):
    username = models.ForeignKey(User,on_delete=models.CASCADE,null=True)
    message = models.CharField(max_length=150)

    def __str__(self):
        return f"nickname:{self.username},message:{self.message}"

tweet_project/tweet_app/views.py
from django.shortcuts import render,redirect
from django.urls import reverse,reverse_lazy
from tweet_app.models import Tweets
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.views.generic import CreateView
from . import models



# Create your views here.

def listtweet(request):
    all_tweets = Tweets.objects.all()
    tweet_dict = {"tweets":all_tweets}
    return render(request,"tweet_app/listtweet.html",context=tweet_dict)


@login_required(login_url="/login")
def addtweet(request):
    if request.method == "POST":
        
        message = request.POST["message"]
        Tweets.objects.create(username=request.user,message=message)
        return redirect(reverse("tweet_app:listtweet"))
    else:
        return render(request,"tweet_app/addtweet.html")


@login_required
def delete(request,id):
    tweet = models.Tweets.objects.get(pk=id)
    if request.user == tweet.username:
        models.Tweets.objects.filter(id=id).delete()
        return redirect(reverse("tweet_app:listtweet"))


class signup(CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy("/login")
    template_name = "registration/signup.html"

tweet_project/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
    <title>Tunanın sözleri</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
        <div class="container-fluid">
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav me-auto mb-2 mb-md-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'tweet_app:listtweet' %}">Tweets</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'tweet_app:addtweet' %}">addtweet</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'login' %}">giriş</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'logout' %}?next=/">çıkış</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'tweet_app:signup' %}">kayıt</a>
              </li>
            </ul>
            
          </div>
        </div>
      </nav>

        {% block content  %}
    
    
    
    
        {% endblock  %}
  </body>
</html>

tweet_project/tweet_app/templates/tweet_app/addtweet.html
{% extends 'base.html' %}
{% block content  %}
<div class="container">
<form method="POST">
  {% csrf_token %}
   
    <div class="mb-3">
      <label for="message" class="form-label">Tweet</label>
      <input type="text" class="form-control" id="message" name="message">
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
</div>
{% endblock  %}

tweet_project/tweet_app/templates/tweet_app/listtweet.html
{% extends 'base.html' %}
    
{% block content  %}
        {% for tweet in tweets  %}
            <div class="card" style="">
                <div class="card-header">
                Tweet
                </div>
                <div class="card-body">
                <blockquote class="blockquote mb-0">
                    <p>{{tweet.message}} </p>
                    <footer class="blockquote-footer">{{tweet.username}}</footer>
                </blockquote>
                </div>
                {% if tweet.username == user %}
                <a href="{% url 'tweet_app:deletetweet' id=tweet.id %}" class="btn btn-danger">delete</a>
                {% endif %}
            </div>
        {% endfor %}

    {% endblock  %}